services:
  service-a:
    build:
      context: .
      args:
        CMD_DIR: ./cmd/service-a/main.go
    container_name: backend-service-a
    ports:
      - 8080:8080
    environment:
      - ENV

  service-b:
    build:
      context: .
      args:
        CMD_DIR: ./cmd/service-b/main.go
    container_name: backend-service-b
    environment:
      - WEATHER_API_KEY
      - ENV

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus export metrics
      - "4317:4317" # OTLP gRPC received
      - "55679:55679"

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"