version: '3.7'

services:
  service-a:
    build:
      context: .
      args:
        CMD_DIR: ./cmd/service-a/main.go
    container_name: backend-service-a
    environment:
      - SERVICE_NAME=service_a
    ports:
      - 8080:8080
    depends_on:
      - otel-collector

  service-b:
    build:
      context: .
      args:
        CMD_DIR: ./cmd/service-b/main.go
    container_name: backend-service-b
    environment:
      - WEATHER_API_KEY
      - SERVICE_NAME=service_b
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC received
      - "4318:4318" # OTLP HTTP received
      - "55679:55679"

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
